baseURL = 'https://bugsecureit.com'
title = 'Bug Secure IT'
author = "Muhammad Wildan Fahrezi"
copyright = "Bug Secure IT"
languageCode = 'en'
defaultContentLanguage = "en"
hasCJKLanguage = true
enableInlineShortcodes = true
# prevent build failures when using Hugo's Instagram shortcode due to deprecated Instagram API.
# See https://github.com/gohugoio/hugo/issues/7228#issuecomment-714490456
ignoreErrors = ["error-remote-getjson"]
theme = "hugo-theme-tailwind"
enableRobotsTXT = true
enableEmoji = true

[markup]
_merge = "deep"

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[markup.highlight]
  # lineNos = true
  noClasses = false
[markup.goldmark]
  [markup.goldmark.renderer]
    unsafe = true
  [markup.goldmark.extensions]
    [markup.goldmark.extensions.cjk]
      enable = true
      eastAsianLineBreaks = true
      escapedSpace = true

[privacy]
  [privacy.vimeo]
    disabled = false
    simple = true

  [privacy.twitter]
    disabled = false
    enableDNT = true
    simple = true

  [privacy.instagram]
    disabled = false
    simple = true

  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

[module]
  [module.hugoVersion]
    extended = false
    min = "0.120.0"
